### ISSUE TITLE
Build to Keybind Mapping

### ISSUE THREAD

**Issue by berdandy** [accessibilitywars/aw2-builds#1]
As mentioned by `@Elsi CastleElsinore.6459` in discord:
> Not sure if this was brought up, or is even possible, but a build to keybind converter would be magical
I.e. it's difficult for me to process names of skills, translate them to my keys, then memorize an order.
But if especially as part of our low impact builds we could integrate something that would skip that middle step and know that (skill) is your Q key so your rotation translates to (list of numbers and letters) instead of "here's some skills, figure it out from a video!"

**Comment by MuwuM** [comment]
![grafik](https://user-images.githubusercontent.com/1980040/164319039-b968f478-e40b-46b9-9bee-a23434419f0c.png)

I created a mockup, how this could be possible

Code could look something like this

```
press <span class="armory-inline" data-aw2-key="F2" data-armory-embed="skills" data-armory-ids="62803" data-armory-size="32"></span> and wait until your charges are full
```

the skill representation would be fetched from `armory-embeds`, the key would be displayed using some [custom css
](https://github.com/MuwuM/aw2-builds/blob/9880d80e9b058e289af51b95f85cfc69c1be6f22/docs/assets/css/main.scss#L10)

We then would need some JavaScript to edit key-binds and store them in localStorage. The JavaScript would also scan the page for Elements with `data-aw2-key="F2"` attributes. If mapping for that key would exist, it would automatically add a `data-aw2-key-mapped="Shift + W"` attribute, that would then be displayed instead of the original key [due to the css](https://github.com/MuwuM/aw2-builds/blob/9880d80e9b058e289af51b95f85cfc69c1be6f22/docs/assets/css/main.scss#L34).

The most difficult part would be to create the setting to edit the key-binding. The rest of the script would be pretty easy to code and robust in execution, as proper CSS fallbacks exists.

EDIT: my prototype can be found here: https://github.com/MuwuM/aw2-builds/tree/armory-embed-gear

Or use [compare link](https://github.com/accessibilitywars/aw2-builds/compare/main...MuwuM:armory-embed-gear) to just see the changes

**Comment by MuwuM** [comment]
Also added Buttons to preview and reset to `data-aw2-key-mapped`

![grafik](https://user-images.githubusercontent.com/1980040/164324143-4f125f1b-20f0-465f-ae32-aab4dfa203ff.png)

**Comment by MuwuM** [comment]
As #19 got merged, I think we can close this issue.

**Comment by berdandy** [comment]
I figured since I assigned it to you, you'd be able to close it. Maybe i have to check permissions.

I'll close it now, at any rate.
